### ISSUE TITLE
Primefaces-excella-exporter doesn't show PrimeIcons

### ISSUE THREAD

**Issue by kinoshita0517** [maruTA-bis5/primefaces-excella-exporter#12]
![image](https://user-images.githubusercontent.com/83056396/115825153-faa7d800-a443-11eb-86e7-179eeed1bbbc.png)

**Comment by maruTA-bis5** [comment]
@kinoshita0517 This issue needs more details about your problem.

You can write more useful reports by read this article. Thanks.  
https://upthemes.com/blog/2014/02/writing-useful-github-issues/

**Comment by maruTA-bis5** [comment]
If you have any questions, please open a new discussion from https://github.com/maruTA-bis5/primefaces-excella-exporter/discussions/new
