### ISSUE TITLE
UIに表示されないタグが出力される

### ISSUE THREAD

**Issue by suenaga0342** [maruTA-bis5/primefaces-excella-exporter#44]
### Describe the bug

excel出力対象のデータテーブルのヘッダーに改行コード（BRタグ）などUIに表示されないタグが含まれている場合に、
それらのコードもexcelに表示されてしまう

### Reproducer: XHTML

```xhtml　
		<p:column>
			<f:facet name="header">
				<h:outputText escape="false" value="タイトル&lt;BR&gt;改行" />
			</f:facet>
			<h:outputText
				value="testText" />
		</p:column>
```

### Expected / Observed behavior
* Expected 
![image](https://user-images.githubusercontent.com/118811477/203294140-be5aa61b-afb4-405d-ad1f-c5cabdeefa69.png)

* Observed behavior
![image](https://user-images.githubusercontent.com/118811477/203291885-dd6c7903-a951-4362-b5c7-93090be452ad.png)

### Jakarta Faces (JSF) Implementation / Version

WildFly

### PrimeFaces Version

11.0.0

### PrimeFaces ExCella Exporter Version

2.0.1

**Comment by maruTA-bis5** [comment]
@suenaga0342 `タイトル`と`改行`の間にスペースは不要と考えていますが相違ありませんか

**Comment by suenaga0342** [comment]
@maruTA-bis5 失礼しました。相違ありません

**Comment by maruTA-bis5** [comment]
FYI: I strongly recommend avoiding using the `escape="false"` attribute because it may occur XSS vulnerability.

**Comment by maruTA-bis5** [comment]
Example:
```xhtml
<p:column>
  <f:facet name="header">
    header<br />line<br />break
  </f:facet>
</p:column>
```
