### ISSUE TITLE
DataTable: `colspan`を複数指定した際にエラーが発生する

### ISSUE THREAD

**Issue by riemr-riemr** [maruTA-bis5/primefaces-excella-exporter#53]
### Describe the bug

<p:column>タグでcolspan属性を指定した際にcolspanの値にかかわらず1行として扱われ、セル結合でエラーが発生する。

### Reproducer: XHTML

```html
  <p:dataTable>
	<p:row>
		<p:column colspan="3" />
		<p:column colspan="2" />
	</p:row>
  </p:dataTable>
```

### Jakarta Faces (JSF) Implementation / Version

WildFly 20.0.1.Final, 26.0.1.Final

### PrimeFaces Version

11.0.0

### PrimeFaces ExCella Exporter Version

2.0.2

**Comment by maruTA-bis5** [comment]
@riemr-riemr このXHTMLだと何も表示されないです。不具合を再現できる情報を提供してもらえませんか?

**Comment by riemr-riemr** [comment]
@maruTA-bis5 
申し訳ありません。
バグの再現XHTMLを作成している際にバグの原因が別にあることに気が付きました。
このissueでのバグは存在しませんでした。
#52 が原因で発生しているバグでした。

**Comment by maruTA-bis5** [comment]
duplicate of #52
