### ISSUE TITLE
DataTable: フッターの結合位置がずれている

### ISSUE THREAD

**Issue by riemr-riemr** [maruTA-bis5/primefaces-excella-exporter#56]
### Describe the bug

フッターの結合位置がずれている。
添付画像ではフッターの一つ下の行が結合されている。

### Reproducer: XHTML

		<p:dataTable id="test" value="test">
			<p:column headerText="A">
				<h:outputText value="1" />
			</p:column>
			<p:column headerText="B">
				<h:outputText value="2" />
			</p:column>
			<p:column headerText="C">
				<h:outputText value="3" />
			</p:column>
			<p:column headerText="D">
				<h:outputText value="4" />
			</p:column>
			<p:column headerText="E">
				<h:outputText value="5" />
			</p:column>
			<p:columnGroup type="footer">
				<p:row>
					<p:column colspan="3" footerText="colspan3" />
					<p:column />
					<p:column />
				</p:row>
			</p:columnGroup>
		</p:dataTable>

### Expected / Observed behavior

**Expected**
![image](https://user-images.githubusercontent.com/91113910/212263173-ebc6d90b-46aa-4096-b058-434568915cb5.png)

**Observed**
![image](https://user-images.githubusercontent.com/91113910/212263007-ad8ba12c-1e97-4e08-8d0c-07a9f222c23e.png)

### Jakarta Faces (JSF) Implementation / Version

WildFly 20.0.1.Final, 26.0.1.Final

### PrimeFaces Version

11.0.0

### PrimeFaces ExCella Exporter Version

2.0.3

**Comment by maruTA-bis5** [comment]
@riemr-riemr デフォルトのテンプレートで出力した場合はどうでしょうか? 問題無いようなら、使用しているテンプレートを提供していただけますか

**Comment by riemr-riemr** [comment]
フッターが表示されない点は使用していたテンプレートファイルの誤りでした。デフォルトテンプレートを用いた場合でも結合位置がずれるようでしたのでissueの記述内容を修正しました。
