### ISSUE TITLE
ValueHolder#getValue() == nullでも指定した値を表示できるようにしてほしい

### ISSUE THREAD

**Issue by achan1g** [maruTA-bis5/primefaces-excella-exporter#61]
- `net.bis5.excella.primefaces.exporter.DataTableExcellaExporter`

**Comment by maruTA-bis5** [comment]
@achan1g 具体的なユースケースを提示していただけますか?

**Comment by achan1g** [comment]
@maruTA-bis5  例えば、ステータスを示すような列を出力する場合に、nullの場合にデフォルト値としてXを表示させたいような場合を想定しています。
